apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir-ingester
spec:
  template:
    spec:
      containers:
      - name: mimir
        resources:
          requests:
            cpu: 1000m
            memory: 4Gi
          limits:
            cpu: 2000m
            memory: 8Gi
        # Enhanced container security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        env:
        - name: CUSTOM_INGESTER_CONFIG
          value: "enabled"
        # Add custom volume mounts
        volumeMounts:
        - name: custom-config
          mountPath: /etc/mimir/custom
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
        - name: data-volume
          mountPath: /data
      # Add custom volumes
      volumes:
      - name: custom-config
        configMap:
          name: mimir-custom-config
      - name: tmp-volume
        emptyDir: {}
      - name: data-volume
        emptyDir: {}
      # Enhanced pod security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      # Node affinity for better distribution
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - ingester
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - compute-optimized